apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: envservice
    context: src/envservice
  - image: translationservice
    context: src/translationservice
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
- name: travis-ci
  build:
    local:
      push: false
#     skaffold run -p gcb
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s