apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: envservice
spec:
  template:
    metadata:
      labels:
        app: envservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: envservice
        imagePullPolicy: Never
        ports:
        - containerPort: 8666
        env:
        - name: PORT
          value: "8666"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: envservice
spec:
  type: ClusterIP
  selector:
    app: envservice
  ports:
  - name: grpc
    port: 8666
    targetPort: 8666
